apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb
  namespace: chatapp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: hostpath
