apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-runtime-config
  labels:
    app: frontend
data:
  config.js: |
    window.__CHATAPP_CONFIG__ = {
      VUE_APP_DEX_ISSUER_URL: "{{ .Values.oidc.issuer }}",
      VUE_APP_DEX_CLIENT_ID: "{{ .Values.oidc.clientId }}",
      VUE_APP_DEX_REDIRECT_URI: "{{ .Values.oidc.redirectUri }}",
      VUE_APP_DEX_SCOPES: "{{ .Values.oidc.scopes }}",
      VUE_APP_API_BASE_URL: "{{ .Values.api.baseUrl }}",
      VUE_APP_WS_URL: "{{ .Values.ws.url }}"
    };
