{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.caBundleName }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  ca.crt: |
{{- if .Values.secrets.caCrt }}
{{ .Values.secrets.caCrt | indent 4 }}
{{- else if .Values.secrets.caCrtFile }}
{{ .Files.Get .Values.secrets.caCrtFile | indent 4 }}
{{- else }}
    # Provide .Values.secrets.caCrtFile to populate content
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.certSecretName }}
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/tls
stringData:
  tls.crt: |
{{- if .Values.secrets.tlsCrt }}
{{ .Values.secrets.tlsCrt | indent 4 }}
{{- else if .Values.secrets.tlsCrtFile }}
{{ .Files.Get .Values.secrets.tlsCrtFile | indent 4 }}
{{- else }}
    # Provide .Values.secrets.tlsCrtFile to populate content
{{- end }}
  tls.key: |
{{- if .Values.secrets.tlsKey }}
{{ .Values.secrets.tlsKey | indent 4 }}
{{- else if .Values.secrets.tlsKeyFile }}
{{ .Files.Get .Values.secrets.tlsKeyFile | indent 4 }}
{{- else }}
    # Provide .Values.secrets.tlsKeyFile to populate content
{{- end }}
{{- end }}
