config:
  # Issuer must match external URL (served under /dex)
  issuer: https://ingress.local/dex  # TLS enabled ingress; ensure cert for ingress.local present

  storage:
    type: memory

  enablePasswordDB: true
  connectors:
    - type: authproxy
      id: local-postgres
      name: Local Accounts
      config:
        userHeader: X-Remote-User
        groupHeader: X-Remote-Group
  # GitHub connector removed for local development. Add back by reinstating a connectors list.
  # connectors:
  #   - type: github
  #     id: github
  #     name: GitHub
  #     config:
  #       clientID: GITHUB_CLIENT_ID
  #       clientSecret: GITHUB_CLIENT_SECRET
  #       redirectURI: http://ingress.local/dex/callback

  staticClients:
    - id: chat-app-frontend
      # SPA client: redirect back to the frontend app route
      redirectURIs:
        - https://ingress.local/callback
      name: Chat App Frontend
      public: true
    - id: backend
      redirectURIs:
        - https://ingress.local/dex/auth/callback
      name: Chat App Backend
      secret: CHAT_APP_BACKEND_SECRET

ingress:
  enabled: true

  annotations:
    cert-manager.io/cluster-issuer: acme
  className: nginx
  
  hosts:
    - host: ingress.local
      paths:
        - path: /dex
          pathType: Prefix
  tls:
    - hosts:
        - ingress.local
      secretName: dex-cert

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi