config:
  # Set it to a valid URL
  issuer: http://ingress.local

  # See https://dexidp.io/docs/storage/ for more options
  storage:
    type: memory

  # Enable at least one connector
  enablePasswordDB: true

  connectors:
    - type: github
      id: github
      name: GitHub
      config:
        clientID: GITHUB_CLIENT_ID
        clientSecret: GITHUB_CLIENT_SECRET
        redirectURI: http://ingress.local/dex/callback

  staticClients:
    - id: chat-app-frontend
      redirectURIs:
        - https://ingress.local/dex/auth/callback
      name: Chat App Frontend
      secret: CHAT_APP_FRONTEND_SECRET
    - id: backend
      redirectURIs:
        - https://ingress.local/dex/auth/callback
      name: Chat App Backend
      secret: CHAT_APP_BACKEND_SECRET

ingress:
  enabled: true

  annotations:
    cert-manager.io/cluster-issuer: acme
  className: nginx
  
  hosts:
    - host: ingress.local
      paths:
        - path: /dex
          pathType: Prefix
  tls:
    - hosts:
        - ingress.local
      secretName: dex-cert