apiVersion: v1
kind: Secret
metadata:
  name: dex-ca-bundle
  namespace: chatapp
type: Opaque
stringData:
  ca.crt: |
    ${CA_CRT}
---
apiVersion: v1
kind: Secret
metadata:
  name: dex-cert
  namespace: chatapp
type: kubernetes.io/tls
stringData:
  tls.crt: |
    ${TLS_CRT}
  tls.key: |
    ${TLS_KEY}